version: '3.9'
services:
  weather-tracker:
    image: krios2146/weather-tracker
    environment:
      JAKARTA_PERSISTENCE_JDBC_URL: jdbc:postgresql://db:5432/weather-tracker
      JAKARTA_PERSISTENCE_JDBC_USER: java
      JAKARTA_PERSISTENCE_JDBC_PASSWORD: java
      HIBERNATE_DDL_AUTO: create-drop
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: java
      POSTGRES_PASSWORD: java
      POSTGRES_DB: weather-tracker
